/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardTeamIdRouteImport } from './routes/dashboard.$teamId'
import { Route as InsightsTeamIdRouteImport } from './routes/insights.$teamId'
import { Route as LeagueLeagueIdRouteImport } from './routes/league.$leagueId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeamIdRoute = DashboardTeamIdRouteImport.update({
  id: '/dashboard/$teamId',
  path: '/dashboard/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsTeamIdRoute = InsightsTeamIdRouteImport.update({
  id: '/insights/$teamId',
  path: '/insights/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdRoute = LeagueLeagueIdRouteImport.update({
  id: '/league/$leagueId',
  path: '/league/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard/$teamId': typeof DashboardTeamIdRoute
  '/insights/$teamId': typeof InsightsTeamIdRoute
  '/league/$leagueId': typeof LeagueLeagueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard/$teamId': typeof DashboardTeamIdRoute
  '/insights/$teamId': typeof InsightsTeamIdRoute
  '/league/$leagueId': typeof LeagueLeagueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard/$teamId': typeof DashboardTeamIdRoute
  '/insights/$teamId': typeof InsightsTeamIdRoute
  '/league/$leagueId': typeof LeagueLeagueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard/$teamId'
    | '/insights/$teamId'
    | '/league/$leagueId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard/$teamId'
    | '/insights/$teamId'
    | '/league/$leagueId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard/$teamId'
    | '/insights/$teamId'
    | '/league/$leagueId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardTeamIdRoute: typeof DashboardTeamIdRoute
  InsightsTeamIdRoute: typeof InsightsTeamIdRoute
  LeagueLeagueIdRoute: typeof LeagueLeagueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$teamId': {
      id: '/dashboard/$teamId'
      path: '/dashboard/$teamId'
      fullPath: '/dashboard/$teamId'
      preLoaderRoute: typeof DashboardTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$teamId': {
      id: '/insights/$teamId'
      path: '/insights/$teamId'
      fullPath: '/insights/$teamId'
      preLoaderRoute: typeof InsightsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId': {
      id: '/league/$leagueId'
      path: '/league/$leagueId'
      fullPath: '/league/$leagueId'
      preLoaderRoute: typeof LeagueLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardTeamIdRoute: DashboardTeamIdRoute,
  InsightsTeamIdRoute: InsightsTeamIdRoute,
  LeagueLeagueIdRoute: LeagueLeagueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
